/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupAuthenticatorRouteImport } from './routes/setup-authenticator'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppBackupsRouteImport } from './routes/_app/backups'
import { Route as AppEnrollmentRouteImport } from './routes/_app/enrollment'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppLicencesRouteImport } from './routes/_app/licences'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions'
import { Route as AppTenantsRouteImport } from './routes/_app/tenants'
import { Route as AppBackupsDeviceIdRouteImport } from './routes/_app/backups.$deviceId'
import { Route as AppFleetDeviceIdRouteImport } from './routes/_app/fleet.$deviceId'
import { Route as AppSubscriptionsIdRouteImport } from './routes/_app/subscriptions.$id'
import { Route as AppTenantsTenantIdRouteImport } from './routes/_app/tenants.$tenantId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAuthenticatorRoute = SetupAuthenticatorRouteImport.update({
  id: '/setup-authenticator',
  path: '/setup-authenticator',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsRoute = AppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentRoute = AppEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppLicencesRoute = AppLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsDeviceIdRoute = AppBackupsDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => AppBackupsRoute,
} as any)
const AppFleetDeviceIdRoute = AppFleetDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => AppFleetRoute,
} as any)
const AppSubscriptionsIdRoute = AppSubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSubscriptionsRoute,
} as any)
const AppTenantsTenantIdRoute = AppTenantsTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AppTenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup-authenticator': typeof SetupAuthenticatorRoute
  '/setup-password': typeof SetupPasswordRoute
  '/audit': typeof AppAuditRoute
  '/backups': typeof AppBackupsRouteWithChildren
  '/enrollment': typeof AppEnrollmentRoute
  '/fleet': typeof AppFleetRouteWithChildren
  '/licences': typeof AppLicencesRoute
  '/plans': typeof AppPlansRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRouteWithChildren
  '/tenants': typeof AppTenantsRouteWithChildren
  '/backups/$deviceId': typeof AppBackupsDeviceIdRoute
  '/fleet/$deviceId': typeof AppFleetDeviceIdRoute
  '/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/tenants/$tenantId': typeof AppTenantsTenantIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup-authenticator': typeof SetupAuthenticatorRoute
  '/setup-password': typeof SetupPasswordRoute
  '/audit': typeof AppAuditRoute
  '/backups': typeof AppBackupsRouteWithChildren
  '/enrollment': typeof AppEnrollmentRoute
  '/fleet': typeof AppFleetRouteWithChildren
  '/licences': typeof AppLicencesRoute
  '/plans': typeof AppPlansRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRouteWithChildren
  '/tenants': typeof AppTenantsRouteWithChildren
  '/': typeof AppIndexRoute
  '/backups/$deviceId': typeof AppBackupsDeviceIdRoute
  '/fleet/$deviceId': typeof AppFleetDeviceIdRoute
  '/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/tenants/$tenantId': typeof AppTenantsTenantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup-authenticator': typeof SetupAuthenticatorRoute
  '/setup-password': typeof SetupPasswordRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/backups': typeof AppBackupsRouteWithChildren
  '/_app/enrollment': typeof AppEnrollmentRoute
  '/_app/fleet': typeof AppFleetRouteWithChildren
  '/_app/licences': typeof AppLicencesRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscriptions': typeof AppSubscriptionsRouteWithChildren
  '/_app/tenants': typeof AppTenantsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/backups/$deviceId': typeof AppBackupsDeviceIdRoute
  '/_app/fleet/$deviceId': typeof AppFleetDeviceIdRoute
  '/_app/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/_app/tenants/$tenantId': typeof AppTenantsTenantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup-authenticator'
    | '/setup-password'
    | '/audit'
    | '/backups'
    | '/enrollment'
    | '/fleet'
    | '/licences'
    | '/plans'
    | '/settings'
    | '/subscriptions'
    | '/tenants'
    | '/backups/$deviceId'
    | '/fleet/$deviceId'
    | '/subscriptions/$id'
    | '/tenants/$tenantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup-authenticator'
    | '/setup-password'
    | '/audit'
    | '/backups'
    | '/enrollment'
    | '/fleet'
    | '/licences'
    | '/plans'
    | '/settings'
    | '/subscriptions'
    | '/tenants'
    | '/'
    | '/backups/$deviceId'
    | '/fleet/$deviceId'
    | '/subscriptions/$id'
    | '/tenants/$tenantId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup-authenticator'
    | '/setup-password'
    | '/_app/audit'
    | '/_app/backups'
    | '/_app/enrollment'
    | '/_app/fleet'
    | '/_app/licences'
    | '/_app/plans'
    | '/_app/settings'
    | '/_app/subscriptions'
    | '/_app/tenants'
    | '/_app/'
    | '/_app/backups/$deviceId'
    | '/_app/fleet/$deviceId'
    | '/_app/subscriptions/$id'
    | '/_app/tenants/$tenantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupAuthenticatorRoute: typeof SetupAuthenticatorRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-authenticator': {
      id: '/setup-authenticator'
      path: '/setup-authenticator'
      fullPath: '/setup-authenticator'
      preLoaderRoute: typeof SetupAuthenticatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backups': {
      id: '/_app/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AppBackupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment': {
      id: '/_app/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof AppEnrollmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/licences': {
      id: '/_app/licences'
      path: '/licences'
      fullPath: '/licences'
      preLoaderRoute: typeof AppLicencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backups/$deviceId': {
      id: '/_app/backups/$deviceId'
      path: '/$deviceId'
      fullPath: '/backups/$deviceId'
      preLoaderRoute: typeof AppBackupsDeviceIdRouteImport
      parentRoute: typeof AppBackupsRoute
    }
    '/_app/fleet/$deviceId': {
      id: '/_app/fleet/$deviceId'
      path: '/$deviceId'
      fullPath: '/fleet/$deviceId'
      preLoaderRoute: typeof AppFleetDeviceIdRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/_app/subscriptions/$id': {
      id: '/_app/subscriptions/$id'
      path: '/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof AppSubscriptionsIdRouteImport
      parentRoute: typeof AppSubscriptionsRoute
    }
    '/_app/tenants/$tenantId': {
      id: '/_app/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AppTenantsTenantIdRouteImport
      parentRoute: typeof AppTenantsRoute
    }
  }
}

interface AppBackupsRouteChildren {
  AppBackupsDeviceIdRoute: typeof AppBackupsDeviceIdRoute
}

const AppBackupsRouteChildren: AppBackupsRouteChildren = {
  AppBackupsDeviceIdRoute: AppBackupsDeviceIdRoute,
}

const AppBackupsRouteWithChildren = AppBackupsRoute._addFileChildren(
  AppBackupsRouteChildren,
)

interface AppFleetRouteChildren {
  AppFleetDeviceIdRoute: typeof AppFleetDeviceIdRoute
}

const AppFleetRouteChildren: AppFleetRouteChildren = {
  AppFleetDeviceIdRoute: AppFleetDeviceIdRoute,
}

const AppFleetRouteWithChildren = AppFleetRoute._addFileChildren(
  AppFleetRouteChildren,
)

interface AppSubscriptionsRouteChildren {
  AppSubscriptionsIdRoute: typeof AppSubscriptionsIdRoute
}

const AppSubscriptionsRouteChildren: AppSubscriptionsRouteChildren = {
  AppSubscriptionsIdRoute: AppSubscriptionsIdRoute,
}

const AppSubscriptionsRouteWithChildren =
  AppSubscriptionsRoute._addFileChildren(AppSubscriptionsRouteChildren)

interface AppTenantsRouteChildren {
  AppTenantsTenantIdRoute: typeof AppTenantsTenantIdRoute
}

const AppTenantsRouteChildren: AppTenantsRouteChildren = {
  AppTenantsTenantIdRoute: AppTenantsTenantIdRoute,
}

const AppTenantsRouteWithChildren = AppTenantsRoute._addFileChildren(
  AppTenantsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBackupsRoute: typeof AppBackupsRouteWithChildren
  AppEnrollmentRoute: typeof AppEnrollmentRoute
  AppFleetRoute: typeof AppFleetRouteWithChildren
  AppLicencesRoute: typeof AppLicencesRoute
  AppPlansRoute: typeof AppPlansRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRouteWithChildren
  AppTenantsRoute: typeof AppTenantsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBackupsRoute: AppBackupsRouteWithChildren,
  AppEnrollmentRoute: AppEnrollmentRoute,
  AppFleetRoute: AppFleetRouteWithChildren,
  AppLicencesRoute: AppLicencesRoute,
  AppPlansRoute: AppPlansRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRouteWithChildren,
  AppTenantsRoute: AppTenantsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupAuthenticatorRoute: SetupAuthenticatorRoute,
  SetupPasswordRoute: SetupPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
