-- 0003 identity, tenancy, devices, subscriptions, entitlements (owner: WT-0).
-- Generated by drizzle-kit from apps/worker-api/src/db/schema.ts, then edited:
--   * `settings` and `audit_log` already exist (0001/0002); audit_log gains columns via ALTER.
--   * seed rows appended: permission catalogue, role grants, plans, tenant code counter.
-- Applies from 0002's state. Timestamps are ISO-8601 UTC text except Better Auth's own columns.

CREATE TABLE `account` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`user_id` text NOT NULL,
	`access_token` text,
	`refresh_token` text,
	`id_token` text,
	`access_token_expires_at` integer,
	`refresh_token_expires_at` integer,
	`scope` text,
	`password` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `account_userId_idx` ON `account` (`user_id`);
--> statement-breakpoint
CREATE TABLE `device_credentials` (
	`id` text PRIMARY KEY NOT NULL,
	`device_id` text NOT NULL,
	`token_hash` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`revoked_at` text,
	FOREIGN KEY (`device_id`) REFERENCES `devices`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `device_credentials_token_hash_unique` ON `device_credentials` (`token_hash`);
--> statement-breakpoint
CREATE INDEX `device_credentials_device_idx` ON `device_credentials` (`device_id`);
--> statement-breakpoint
CREATE TABLE `devices` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`name` text NOT NULL,
	`status` text DEFAULT 'enrolled' NOT NULL,
	`device_public_key_jwk` text NOT NULL,
	`device_key_thumbprint` text NOT NULL,
	`key_protection` text NOT NULL,
	`hostname` text NOT NULL,
	`windows_build` text,
	`agent_version` text,
	`last_seen_at` text,
	`last_health_json` text,
	`enrolled_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`revoked_at` text,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "devices_status_check" CHECK("devices"."status" IN ('enrolled', 'revoked', 'transferred')),
	CONSTRAINT "devices_key_protection_check" CHECK("devices"."key_protection" IN ('tpm', 'software'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `devices_device_key_thumbprint_unique` ON `devices` (`device_key_thumbprint`);
--> statement-breakpoint
CREATE INDEX `devices_tenant_status_idx` ON `devices` (`tenant_id`,`status`);
--> statement-breakpoint
CREATE TABLE `enrollment_tokens` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`token_hash` text NOT NULL,
	`label` text NOT NULL,
	`created_by` text NOT NULL,
	`expires_at` text NOT NULL,
	`redeemed_at` text,
	`redeemed_device_id` text,
	`revoked_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`redeemed_device_id`) REFERENCES `devices`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `enrollment_tokens_token_hash_unique` ON `enrollment_tokens` (`token_hash`);
--> statement-breakpoint
CREATE INDEX `enrollment_tokens_tenant_idx` ON `enrollment_tokens` (`tenant_id`,`created_at`);
--> statement-breakpoint
CREATE TABLE `entitlements` (
	`id` text PRIMARY KEY NOT NULL,
	`subscription_id` text NOT NULL,
	`device_id` text NOT NULL,
	`generation` integer NOT NULL,
	`claims_json` text NOT NULL,
	`token` text NOT NULL,
	`issued_by` text NOT NULL,
	`issued_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`valid_until` text NOT NULL,
	`revoked_at` text,
	FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`device_id`) REFERENCES `devices`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `entitlements_device_generation_uq` ON `entitlements` (`device_id`,`generation`);
--> statement-breakpoint
CREATE INDEX `entitlements_subscription_idx` ON `entitlements` (`subscription_id`);
--> statement-breakpoint
CREATE TABLE `permissions` (
	`key` text PRIMARY KEY NOT NULL,
	`description` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `plans` (
	`code` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`max_devices` integer NOT NULL,
	`max_managed_users` integer NOT NULL,
	`features_json` text NOT NULL,
	`offline_grace_days` integer NOT NULL,
	`renewal_warning_days` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `role_permissions` (
	`role` text NOT NULL,
	`permission_key` text NOT NULL,
	PRIMARY KEY(`role`, `permission_key`),
	FOREIGN KEY (`permission_key`) REFERENCES `permissions`(`key`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "role_permissions_role_check" CHECK("role_permissions"."role" IN ('super_admin', 'admin', 'support', 'read_only'))
);
--> statement-breakpoint
CREATE TABLE `session` (
	`id` text PRIMARY KEY NOT NULL,
	`expires_at` integer NOT NULL,
	`token` text NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer NOT NULL,
	`ip_address` text,
	`user_agent` text,
	`user_id` text NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `session_token_unique` ON `session` (`token`);
--> statement-breakpoint
CREATE INDEX `session_userId_idx` ON `session` (`user_id`);
--> statement-breakpoint
CREATE TABLE `signing_keys` (
	`kid` text PRIMARY KEY NOT NULL,
	`alg` text NOT NULL,
	`public_jwk` text NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	CONSTRAINT "signing_keys_status_check" CHECK("signing_keys"."status" IN ('active', 'retired'))
);
--> statement-breakpoint
CREATE TABLE `staff_members` (
	`user_id` text PRIMARY KEY NOT NULL,
	`role` text NOT NULL,
	`created_by` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "staff_members_role_check" CHECK("staff_members"."role" IN ('super_admin', 'admin', 'support', 'read_only'))
);
--> statement-breakpoint
CREATE TABLE `subscriptions` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`plan_code` text NOT NULL,
	`status` text NOT NULL,
	`valid_from` text NOT NULL,
	`valid_until` text NOT NULL,
	`max_managed_users` integer NOT NULL,
	`features_json` text NOT NULL,
	`offline_grace_days` integer NOT NULL,
	`renewal_warning_days` integer NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`plan_code`) REFERENCES `plans`(`code`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "subscriptions_status_check" CHECK("subscriptions"."status" IN ('trial', 'active', 'past_due', 'suspended', 'cancelled'))
);
--> statement-breakpoint
CREATE INDEX `subscriptions_tenant_status_idx` ON `subscriptions` (`tenant_id`,`status`);
--> statement-breakpoint
CREATE TABLE `tenant_memberships` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`user_id` text NOT NULL,
	`standing` text NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`invited_by` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "tenant_memberships_standing_check" CHECK("tenant_memberships"."standing" IN ('owner', 'admin', 'user')),
	CONSTRAINT "tenant_memberships_status_check" CHECK("tenant_memberships"."status" IN ('active', 'revoked'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `tenant_memberships_tenant_user_uq` ON `tenant_memberships` (`tenant_id`,`user_id`);
--> statement-breakpoint
CREATE INDEX `tenant_memberships_user_idx` ON `tenant_memberships` (`user_id`,`status`);
--> statement-breakpoint
CREATE TABLE `tenants` (
	`id` text PRIMARY KEY NOT NULL,
	`public_code` text NOT NULL,
	`display_name` text NOT NULL,
	`legal_name` text,
	`status` text DEFAULT 'provisioning' NOT NULL,
	`primary_contact_email` text,
	`support_contact_email` text,
	`billing_contact_email` text,
	`timezone` text DEFAULT 'UTC' NOT NULL,
	`maintenance_window_json` text,
	`renewal_warning_days` integer DEFAULT 30 NOT NULL,
	`backup_policy_json` text,
	`plan_code` text,
	`notes` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`archived_at` text,
	FOREIGN KEY (`plan_code`) REFERENCES `plans`(`code`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "tenants_status_check" CHECK("tenants"."status" IN ('trial', 'provisioning', 'active', 'past_due', 'suspended', 'cancelled', 'archived'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `tenants_public_code_unique` ON `tenants` (`public_code`);
--> statement-breakpoint
CREATE INDEX `tenants_status_idx` ON `tenants` (`status`,`created_at`);
--> statement-breakpoint
CREATE TABLE `user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);
--> statement-breakpoint
CREATE TABLE `verification` (
	`id` text PRIMARY KEY NOT NULL,
	`identifier` text NOT NULL,
	`value` text NOT NULL,
	`expires_at` integer NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `verification_identifier_idx` ON `verification` (`identifier`);

--> statement-breakpoint

-- ─── audit_log: tenant, correlation and source context ────────────────────────────────────────
ALTER TABLE `audit_log` ADD COLUMN `actor_tenant_id` text;
ALTER TABLE `audit_log` ADD COLUMN `correlation_id` text;
ALTER TABLE `audit_log` ADD COLUMN `source` text;
CREATE INDEX `audit_log_actor_tenant_idx` ON `audit_log` (`actor_tenant_id`,`created_at`);

-- ─── Permission catalogue (master spec) ───────────────────────────────────────────────────────
INSERT INTO `permissions` (`key`, `description`) VALUES
  ('tenant.view', 'View tenants and their memberships'),
  ('tenant.manage', 'Create, edit and archive tenants and memberships'),
  ('subscription.view', 'View plans and subscriptions'),
  ('subscription.manage', 'Create and change subscriptions'),
  ('device.view', 'View fleet devices and health'),
  ('device.manage', 'Enroll, rename and revoke devices'),
  ('device.command', 'Send operational commands to devices'),
  ('device.break_glass', 'Use break-glass support access on a device'),
  ('license.issue', 'Issue device entitlements'),
  ('license.renew', 'Renew device entitlements'),
  ('license.revoke', 'Revoke device entitlements'),
  ('network.view', 'View network state'),
  ('network.manage', 'Change network configuration'),
  ('backup.view', 'View backup state'),
  ('backup.restore', 'Start a backup restore'),
  ('update.view', 'View releases and update state'),
  ('update.release', 'Publish a release'),
  ('update.deploy', 'Deploy a release to devices'),
  ('audit.view', 'Read the audit log'),
  ('staff.manage', 'Add, change and remove staff members'),
  ('settings.manage', 'Change control-plane settings');

-- ─── Role grants, stored as rows (no super-admin bypass in code) ──────────────────────────────
INSERT INTO `role_permissions` (`role`, `permission_key`)
  SELECT 'super_admin', `key` FROM `permissions`;
INSERT INTO `role_permissions` (`role`, `permission_key`)
  SELECT 'admin', `key` FROM `permissions`
  WHERE `key` NOT IN ('staff.manage', 'device.break_glass', 'license.revoke');
INSERT INTO `role_permissions` (`role`, `permission_key`)
  SELECT 'support', `key` FROM `permissions`
  WHERE `key` LIKE '%.view' OR `key` = 'device.command';
INSERT INTO `role_permissions` (`role`, `permission_key`)
  SELECT 'read_only', `key` FROM `permissions` WHERE `key` LIKE '%.view';

-- ─── Plans ────────────────────────────────────────────────────────────────────────────────────
INSERT INTO `plans`
  (`code`, `name`, `max_devices`, `max_managed_users`, `features_json`, `offline_grace_days`, `renewal_warning_days`)
VALUES
  ('cloudbox-6', 'CloudBox 6', 1, 6, '["remote_access","managed_backup","fleet"]', 7, 30);

-- ─── Tenant public code counter: next allocation is CBX-00001 ─────────────────────────────────
INSERT INTO `settings` (`key`, `value_json`, `updated_at`)
VALUES ('tenants.next_code', '1', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
