-- 0004 auth (owner: WT-1): the staff second factor (Better Auth twoFactor → staff_two_factor) and
-- Better Auth's D1 rate-limit storage for each identity system (staff_rate_limit, customer_rate_limit;
-- also CloudBox's per-client counters, src/auth/counters.ts). Generated by drizzle-kit from
-- src/db/schema.ts. Rewritten in place before any deploy.
CREATE TABLE `staff_two_factor` (
	`id` text PRIMARY KEY NOT NULL,
	`secret` text NOT NULL,
	`backup_codes` text NOT NULL,
	`user_id` text NOT NULL,
	`verified` integer DEFAULT true,
	`failed_verification_count` integer DEFAULT 0,
	`locked_until` integer,
	FOREIGN KEY (`user_id`) REFERENCES `staff_users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `staffTwoFactor_secret_idx` ON `staff_two_factor` (`secret`);
--> statement-breakpoint
CREATE INDEX `staffTwoFactor_userId_idx` ON `staff_two_factor` (`user_id`);
--> statement-breakpoint
CREATE TABLE `staff_rate_limit` (
	`id` text PRIMARY KEY NOT NULL,
	`key` text NOT NULL,
	`count` integer NOT NULL,
	`last_request` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `staff_rate_limit_key_unique` ON `staff_rate_limit` (`key`);
--> statement-breakpoint
CREATE TABLE `customer_rate_limit` (
	`id` text PRIMARY KEY NOT NULL,
	`key` text NOT NULL,
	`count` integer NOT NULL,
	`last_request` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `customer_rate_limit_key_unique` ON `customer_rate_limit` (`key`);
