-- 0016 OTA release management, cloud side (owner: WT-18). Master spec §18, §45; Slices 10.1–10.4.
-- Generated by drizzle-kit from src/db/schema.ts, then hand-extended with the trigger block below
-- (D1/SQLite cannot pair `ALTER TABLE ADD COLUMN` with an inline CHECK — same idiom migration 0009
-- uses for `plans.status`/`plans.currency`). `releases`/`release_assignments`/`release_results` are
-- brand-new tables, so their CHECKs are declared inline as drizzle-kit emitted them.
CREATE TABLE `release_assignments` (
	`id` text PRIMARY KEY NOT NULL,
	`release_id` text NOT NULL,
	`scope` text NOT NULL,
	`device_id` text,
	`tenant_id` text,
	`percent` integer,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`release_id`) REFERENCES `releases`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`device_id`) REFERENCES `devices`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "release_assignments_scope_check" CHECK("release_assignments"."scope" IN ('device', 'tenant', 'fleet_percent'))
);
--> statement-breakpoint
CREATE INDEX `release_assignments_release_idx` ON `release_assignments` (`release_id`);--> statement-breakpoint
CREATE INDEX `release_assignments_device_idx` ON `release_assignments` (`device_id`);--> statement-breakpoint
CREATE INDEX `release_assignments_tenant_idx` ON `release_assignments` (`tenant_id`);--> statement-breakpoint
CREATE TABLE `release_results` (
	`id` text PRIMARY KEY NOT NULL,
	`release_id` text NOT NULL,
	`device_id` text NOT NULL,
	`state` text NOT NULL,
	`detail_json` text,
	`reported_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`release_id`) REFERENCES `releases`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`device_id`) REFERENCES `devices`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "release_results_state_check" CHECK("release_results"."state" IN ('assigned', 'downloaded', 'verified', 'installed_healthy', 'installed_unhealthy', 'rolled_back', 'failed_download', 'failed_validation', 'deferred_active_users', 'deferred_maintenance'))
);
--> statement-breakpoint
CREATE INDEX `release_results_release_idx` ON `release_results` (`release_id`,`reported_at`);--> statement-breakpoint
CREATE INDEX `release_results_device_idx` ON `release_results` (`device_id`,`reported_at`);--> statement-breakpoint
CREATE TABLE `releases` (
	`id` text PRIMARY KEY NOT NULL,
	`component` text NOT NULL,
	`version` text NOT NULL,
	`channel` text NOT NULL,
	`manifest_json` text NOT NULL,
	`manifest_jws` text NOT NULL,
	`package_r2_key` text NOT NULL,
	`package_sha256` text NOT NULL,
	`package_size` integer NOT NULL,
	`min_agent_version` text,
	`rollback_of` text,
	`notes` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`promoted_at` text,
	`withdrawn_at` text,
	`withdraw_reason` text,
	CONSTRAINT "releases_component_check" CHECK("releases"."component" IN ('agent', 'status', 'setup', 'connect')),
	CONSTRAINT "releases_channel_check" CHECK("releases"."channel" IN ('development', 'pilot', 'stable', 'pinned')),
	CONSTRAINT "releases_status_check" CHECK("releases"."status" IN ('draft', 'pilot', 'stable', 'withdrawn'))
);
--> statement-breakpoint
CREATE INDEX `releases_component_channel_idx` ON `releases` (`component`,`channel`,`status`);--> statement-breakpoint
CREATE INDEX `releases_created_at_idx` ON `releases` (`created_at`);--> statement-breakpoint
ALTER TABLE `signing_keys` ADD `purpose` text DEFAULT 'entitlement' NOT NULL;

CREATE TRIGGER IF NOT EXISTS signing_keys_purpose_check_insert
BEFORE INSERT ON signing_keys
WHEN NEW.purpose NOT IN ('entitlement', 'release')
BEGIN
  SELECT RAISE(ABORT, 'signing_keys.purpose must be entitlement or release');
END;

CREATE TRIGGER IF NOT EXISTS signing_keys_purpose_check_update
BEFORE UPDATE ON signing_keys
WHEN NEW.purpose NOT IN ('entitlement', 'release')
BEGIN
  SELECT RAISE(ABORT, 'signing_keys.purpose must be entitlement or release');
END;