-- 0019 licence hold (WT-14 follow-up, found by WT-10): a staff licence revoke holds the device so
-- heartbeat auto-issuance cannot undo it; only a staff Issue/Renew clears it. Generated by drizzle-kit.
ALTER TABLE `devices` ADD `license_hold_reason` text;--> statement-breakpoint
ALTER TABLE `devices` ADD `license_hold_at` text;--> statement-breakpoint
ALTER TABLE `devices` ADD `license_hold_by` text;