// Owner: WT-0. Proves db/schema.ts (the Drizzle source of truth) and the applied SQL migrations
// (0001-0010, via test/apply-migrations.ts) agree: every Drizzle table exists in the real D1
// database and every Drizzle column exists with the same NOT NULL-ness. Guards against the
// snapshot/journal drifting from schema.ts again (P2-7).
import { env } from "cloudflare:test";
import { getTableColumns, getTableName, isTable } from "drizzle-orm";
import type { SQLiteTable } from "drizzle-orm/sqlite-core";
import { describe, expect, it } from "vitest";
import * as schema from "../src/db/schema";

interface ColumnRow {
  name: string;
  notnull: number;
}

async function columnsOf(db: D1Database, table: string): Promise<Map<string, boolean>> {
  const { results } = await db.prepare(`PRAGMA table_info(${table})`).all<ColumnRow>();
  return new Map(results.map((r) => [r.name, r.notnull === 1]));
}

// Only plain Drizzle tables (skip relations, enum arrays, and Better Auth's generated tables,
// which are owned by src/auth and regenerated by `auth:generate`, not by this parity check).
const BETTER_AUTH_TABLES = new Set([
  "staff_users",
  "staff_sessions",
  "staff_accounts",
  "staff_verifications",
  "staff_two_factor",
  "customer_users",
  "customer_sessions",
  "customer_accounts",
  "customer_verifications",
]);

describe("schema parity: db/schema.ts matches the applied migrations", () => {
  const tables = Object.values(schema).filter(isTable) as SQLiteTable[];

  it("found the expected number of Drizzle tables", () => {
    expect(tables.length).toBeGreaterThanOrEqual(20);
  });

  for (const table of tables) {
    const tableName = getTableName(table);
    if (BETTER_AUTH_TABLES.has(tableName)) continue;

    it(`${tableName}: every Drizzle column exists with matching NOT NULL`, async () => {
      const actual = await columnsOf(env.DB, tableName);
      expect(actual.size, `table "${tableName}" does not exist in D1`).toBeGreaterThan(0);

      const expectedColumns = getTableColumns(table);
      for (const column of Object.values(expectedColumns)) {
        expect(actual.has(column.name), `"${tableName}.${column.name}" is missing in D1`).toBe(
          true,
        );
        expect(
          actual.get(column.name),
          `"${tableName}.${column.name}" NOT NULL mismatch (schema.ts: ${column.notNull}, D1: ${actual.get(column.name)})`,
        ).toBe(column.notNull);
      }
    });
  }
});
