// Owner: WT-0. The single Drizzle schema for D1. Other worktrees request columns via their handoff.
// Better Auth tables are generated (`pnpm auth:generate`) from src/auth; do not hand-edit them.
// Our timestamps are ISO-8601 UTC text; Better Auth's are its generated integer millis.
import { relations, sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

const isoNow = sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`;
const createdAt = () => text("created_at").notNull().default(isoNow);

// ─── Phase 0 (migrations 0001/0002, extended by 0003) ─────────────────────────────────────────

export const settings = sqliteTable("settings", {
  key: text("key").primaryKey().notNull(),
  valueJson: text("value_json").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const auditLog = sqliteTable(
  "audit_log",
  {
    id: text("id").primaryKey().notNull(),
    eventType: text("event_type").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    actorType: text("actor_type").notNull(),
    actorId: text("actor_id").notNull(),
    action: text("action").notNull(),
    beforeJson: text("before_json"),
    afterJson: text("after_json"),
    createdAt: text("created_at").notNull(),
    actorTenantId: text("actor_tenant_id"),
    correlationId: text("correlation_id"),
    source: text("source"),
  },
  (table) => [
    index("audit_log_created_at_idx").on(table.createdAt),
    index("audit_log_entity_idx").on(table.entityType, table.entityId, table.createdAt),
    index("audit_log_actor_tenant_idx").on(table.actorTenantId, table.createdAt),
  ],
);

// ─── Identity: two separate systems, nothing shared (owner decision, ADR 0002) ─────────────────
// Generated by `auth@1.7.6 generate` from src/auth/cli.ts (staff: password + twoFactor) and
// src/auth/cli-customer.ts (customers: emailOTP). Regenerate both when either plugin list changes.

// Staff identity (/api/ops/auth): staff_users, staff_sessions, staff_accounts, staff_verifications,
// staff_two_factor, staff_rate_limit.
export const staffUsers = sqliteTable("staff_users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" }).default(false).notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  twoFactorEnabled: integer("two_factor_enabled", { mode: "boolean" }).default(false),
});

export const staffSessions = sqliteTable(
  "staff_sessions",
  {
    id: text("id").primaryKey(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => staffUsers.id, { onDelete: "cascade" }),
  },
  (table) => [index("staffSessions_userId_idx").on(table.userId)],
);

export const staffAccounts = sqliteTable(
  "staff_accounts",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => staffUsers.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("staffAccounts_userId_idx").on(table.userId)],
);

export const staffVerifications = sqliteTable(
  "staff_verifications",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("staffVerifications_identifier_idx").on(table.identifier)],
);

export const staffTwoFactor = sqliteTable(
  "staff_two_factor",
  {
    id: text("id").primaryKey(),
    secret: text("secret").notNull(),
    backupCodes: text("backup_codes").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => staffUsers.id, { onDelete: "cascade" }),
    verified: integer("verified", { mode: "boolean" }).default(true),
    failedVerificationCount: integer("failed_verification_count").default(0),
    lockedUntil: integer("locked_until", { mode: "timestamp_ms" }),
  },
  (table) => [
    index("staffTwoFactor_secret_idx").on(table.secret),
    index("staffTwoFactor_userId_idx").on(table.userId),
  ],
);

export const staffRateLimit = sqliteTable("staff_rate_limit", {
  id: text("id").primaryKey(),
  key: text("key").notNull().unique(),
  count: integer("count").notNull(),
  lastRequest: integer("last_request").notNull(),
});

export const staffUsersRelations = relations(staffUsers, ({ many }) => ({
  staffSessionss: many(staffSessions),
  staffAccountss: many(staffAccounts),
  staffTwoFactors: many(staffTwoFactor),
}));

export const staffSessionsRelations = relations(staffSessions, ({ one }) => ({
  staffUsers: one(staffUsers, {
    fields: [staffSessions.userId],
    references: [staffUsers.id],
  }),
}));

export const staffAccountsRelations = relations(staffAccounts, ({ one }) => ({
  staffUsers: one(staffUsers, {
    fields: [staffAccounts.userId],
    references: [staffUsers.id],
  }),
}));

export const staffTwoFactorRelations = relations(staffTwoFactor, ({ one }) => ({
  staffUsers: one(staffUsers, {
    fields: [staffTwoFactor.userId],
    references: [staffUsers.id],
  }),
}));

// Customer identity (/api/auth): customer_users, customer_sessions, customer_accounts,
// customer_verifications, customer_rate_limit.
export const customerUsers = sqliteTable("customer_users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" }).default(false).notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const customerSessions = sqliteTable(
  "customer_sessions",
  {
    id: text("id").primaryKey(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => customerUsers.id, { onDelete: "cascade" }),
  },
  (table) => [index("customerSessions_userId_idx").on(table.userId)],
);

export const customerAccounts = sqliteTable(
  "customer_accounts",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => customerUsers.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("customerAccounts_userId_idx").on(table.userId)],
);

export const customerVerifications = sqliteTable(
  "customer_verifications",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("customerVerifications_identifier_idx").on(table.identifier)],
);

export const customerRateLimit = sqliteTable("customer_rate_limit", {
  id: text("id").primaryKey(),
  key: text("key").notNull().unique(),
  count: integer("count").notNull(),
  lastRequest: integer("last_request").notNull(),
});

export const customerUsersRelations = relations(customerUsers, ({ many }) => ({
  customerSessionss: many(customerSessions),
  customerAccountss: many(customerAccounts),
}));

export const customerSessionsRelations = relations(customerSessions, ({ one }) => ({
  customerUsers: one(customerUsers, {
    fields: [customerSessions.userId],
    references: [customerUsers.id],
  }),
}));

export const customerAccountsRelations = relations(customerAccounts, ({ one }) => ({
  customerUsers: one(customerUsers, {
    fields: [customerAccounts.userId],
    references: [customerUsers.id],
  }),
}));

// ─── Staff and permissions ────────────────────────────────────────────────────────────────────

export const STAFF_ROLES = ["super_admin", "admin", "support", "read_only"] as const;
const staffRoleCheck = sql`('super_admin', 'admin', 'support', 'read_only')`;

export const staffMembers = sqliteTable(
  "staff_members",
  {
    userId: text("user_id")
      .primaryKey()
      .references(() => staffUsers.id),
    role: text("role", { enum: STAFF_ROLES }).notNull(),
    createdBy: text("created_by"),
    createdAt: createdAt(),
    /** 1 until the staff member replaces the initial password an admin set (ADR 0009, WT-1). */
    mustChangePassword: integer("must_change_password", { mode: "boolean" })
      .notNull()
      .default(true),
  },
  (table) => [check("staff_members_role_check", sql`${table.role} IN ${staffRoleCheck}`)],
);

export const permissions = sqliteTable("permissions", {
  key: text("key").primaryKey(),
  description: text("description").notNull(),
});

export const rolePermissions = sqliteTable(
  "role_permissions",
  {
    role: text("role", { enum: STAFF_ROLES }).notNull(),
    permissionKey: text("permission_key")
      .notNull()
      .references(() => permissions.key),
  },
  (table) => [
    primaryKey({ columns: [table.role, table.permissionKey] }),
    check("role_permissions_role_check", sql`${table.role} IN ${staffRoleCheck}`),
  ],
);

// ─── Plans ────────────────────────────────────────────────────────────────────────────────────

export const PLAN_STATUSES = ["active", "retired"] as const;
export const PLAN_CURRENCIES = ["INR", "USD", "EUR", "GBP", "AED"] as const;

// `status`/`term_days` were added to an existing table by migration 0009 via `ALTER TABLE ADD
// COLUMN`, which D1/SQLite cannot pair with an inline CHECK constraint (that requires a full
// table rebuild). Migration 0009 enforces both instead with BEFORE INSERT/UPDATE triggers
// (`plans_status_check_insert/_update`, `plans_term_days_check_insert/_update`) — there is no
// declarative CHECK on this table in D1, so none is declared here either. Migration 0011's
// `currency` column follows the same pattern (`plans_currency_check_insert/_update`); the price
// amounts and `max_addon_users` are plain non-negative integers, bounds enforced by Zod only
// (same as `offline_grace_days`/`renewal_warning_days` above — no DB trigger for those either).
export const plans = sqliteTable("plans", {
  code: text("code").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  maxDevices: integer("max_devices").notNull(),
  maxManagedUsers: integer("max_managed_users").notNull(),
  featuresJson: text("features_json").notNull(),
  offlineGraceDays: integer("offline_grace_days").notNull(),
  renewalWarningDays: integer("renewal_warning_days").notNull(),
  status: text("status").notNull().default("active"),
  /** Days a redeemed subscription runs (owner addition; redemption semantics are WT-14's). */
  termDays: integer("term_days").notNull().default(365),
  /** Minor units (e.g. paise/cents) for `currency`. */
  priceAmount: integer("price_amount").notNull().default(0),
  /** ISO 4217. */
  currency: text("currency").notNull().default("INR"),
  /** Minor units, per additional managed user per term. */
  addonUserPriceAmount: integer("addon_user_price_amount").notNull().default(0),
  /** 0 = no add-on users allowed on this plan. */
  maxAddonUsers: integer("max_addon_users").notNull().default(0),
  createdAt: createdAt(),
  updatedAt: text("updated_at").notNull().default(isoNow),
});

// ─── Tenancy ──────────────────────────────────────────────────────────────────────────────────

export const TENANT_STATUSES = [
  "trial",
  "provisioning",
  "active",
  "past_due",
  "suspended",
  "cancelled",
  "archived",
] as const;

export const tenants = sqliteTable(
  "tenants",
  {
    id: text("id").primaryKey(),
    publicCode: text("public_code").notNull().unique(),
    displayName: text("display_name").notNull(),
    legalName: text("legal_name"),
    status: text("status", { enum: TENANT_STATUSES }).notNull().default("provisioning"),
    primaryContactEmail: text("primary_contact_email"),
    supportContactEmail: text("support_contact_email"),
    billingContactEmail: text("billing_contact_email"),
    timezone: text("timezone").notNull().default("UTC"),
    maintenanceWindowJson: text("maintenance_window_json"),
    renewalWarningDays: integer("renewal_warning_days").notNull().default(30),
    backupPolicyJson: text("backup_policy_json"),
    planCode: text("plan_code").references(() => plans.code),
    notes: text("notes"),
    createdAt: createdAt(),
    updatedAt: text("updated_at").notNull().default(isoNow),
    archivedAt: text("archived_at"),
  },
  (table) => [
    index("tenants_status_idx").on(table.status, table.createdAt),
    check(
      "tenants_status_check",
      sql`${table.status} IN ('trial', 'provisioning', 'active', 'past_due', 'suspended', 'cancelled', 'archived')`,
    ),
  ],
);

export const MEMBERSHIP_STANDINGS = ["owner", "admin", "user"] as const;

export const tenantMemberships = sqliteTable(
  "tenant_memberships",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    userId: text("user_id")
      .notNull()
      .references(() => customerUsers.id),
    standing: text("standing", { enum: MEMBERSHIP_STANDINGS }).notNull(),
    status: text("status", { enum: ["active", "revoked"] })
      .notNull()
      .default("active"),
    invitedBy: text("invited_by"),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex("tenant_memberships_tenant_user_uq").on(table.tenantId, table.userId),
    index("tenant_memberships_user_idx").on(table.userId, table.status),
    check(
      "tenant_memberships_standing_check",
      sql`${table.standing} IN ('owner', 'admin', 'user')`,
    ),
    check("tenant_memberships_status_check", sql`${table.status} IN ('active', 'revoked')`),
  ],
);

// ─── Devices and enrollment ───────────────────────────────────────────────────────────────────

export const devices = sqliteTable(
  "devices",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    name: text("name").notNull(),
    status: text("status", { enum: ["enrolled", "revoked", "transferred"] })
      .notNull()
      .default("enrolled"),
    devicePublicKeyJwk: text("device_public_key_jwk").notNull(),
    deviceKeyThumbprint: text("device_key_thumbprint").notNull().unique(),
    keyProtection: text("key_protection", { enum: ["tpm", "software"] }).notNull(),
    hostname: text("hostname").notNull(),
    windowsBuild: text("windows_build"),
    agentVersion: text("agent_version"),
    lastSeenAt: text("last_seen_at"),
    lastHealthJson: text("last_health_json"),
    enrolledAt: text("enrolled_at").notNull().default(isoNow),
    revokedAt: text("revoked_at"),
  },
  (table) => [
    index("devices_tenant_status_idx").on(table.tenantId, table.status),
    check("devices_status_check", sql`${table.status} IN ('enrolled', 'revoked', 'transferred')`),
    check("devices_key_protection_check", sql`${table.keyProtection} IN ('tpm', 'software')`),
  ],
);

export const enrollmentTokens = sqliteTable(
  "enrollment_tokens",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    tokenHash: text("token_hash").notNull().unique(),
    label: text("label").notNull(),
    createdBy: text("created_by").notNull(),
    expiresAt: text("expires_at").notNull(),
    redeemedAt: text("redeemed_at"),
    redeemedDeviceId: text("redeemed_device_id").references(() => devices.id),
    revokedAt: text("revoked_at"),
    createdAt: createdAt(),
  },
  (table) => [index("enrollment_tokens_tenant_idx").on(table.tenantId, table.createdAt)],
);

export const deviceCredentials = sqliteTable(
  "device_credentials",
  {
    id: text("id").primaryKey(),
    deviceId: text("device_id")
      .notNull()
      .references(() => devices.id),
    tokenHash: text("token_hash").notNull().unique(),
    createdAt: createdAt(),
    revokedAt: text("revoked_at"),
  },
  (table) => [index("device_credentials_device_idx").on(table.deviceId)],
);

// ─── Subscriptions and entitlements ───────────────────────────────────────────────────────────

export const subscriptions = sqliteTable(
  "subscriptions",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    planCode: text("plan_code")
      .notNull()
      .references(() => plans.code),
    // `pending` (migration 0010, WT-14): plan assigned, no dates until the first server activates.
    status: text("status", {
      enum: ["pending", "trial", "active", "past_due", "suspended", "cancelled"],
    }).notNull(),
    validFrom: text("valid_from"),
    validUntil: text("valid_until"),
    maxManagedUsers: integer("max_managed_users").notNull(),
    /**
     * Add-on managed users beyond the plan's base `max_managed_users`, bought at
     * `plans.addon_user_price_amount` each per term (migration 0011). Capped at
     * `plans.max_addon_users`; effective limit = `max_managed_users + addon_users`. Added by
     * `ALTER TABLE ADD COLUMN`, so a constant default only — the `<= max_addon_users` bound is
     * data-dependent (another table) and is enforced by the API, not a DB CHECK.
     */
    addonUsers: integer("addon_users").notNull().default(0),
    featuresJson: text("features_json").notNull(),
    offlineGraceDays: integer("offline_grace_days").notNull(),
    renewalWarningDays: integer("renewal_warning_days").notNull(),
    createdAt: createdAt(),
    updatedAt: text("updated_at").notNull().default(isoNow),
  },
  (table) => [
    index("subscriptions_tenant_status_idx").on(table.tenantId, table.status),
    check(
      "subscriptions_status_check",
      sql`${table.status} IN ('pending', 'trial', 'active', 'past_due', 'suspended', 'cancelled')`,
    ),
    check(
      "subscriptions_dates_check",
      sql`${table.status} = 'pending' OR (${table.validFrom} IS NOT NULL AND ${table.validUntil} IS NOT NULL)`,
    ),
  ],
);

export const entitlements = sqliteTable(
  "entitlements",
  {
    id: text("id").primaryKey(),
    subscriptionId: text("subscription_id")
      .notNull()
      .references(() => subscriptions.id),
    deviceId: text("device_id")
      .notNull()
      .references(() => devices.id),
    generation: integer("generation").notNull(),
    claimsJson: text("claims_json").notNull(),
    /** Compact JWE. Never logged, never returned to the admin UI. */
    token: text("token").notNull(),
    issuedBy: text("issued_by").notNull(),
    issuedAt: text("issued_at").notNull().default(isoNow),
    validUntil: text("valid_until").notNull(),
    revokedAt: text("revoked_at"),
  },
  (table) => [
    uniqueIndex("entitlements_device_generation_uq").on(table.deviceId, table.generation),
    index("entitlements_subscription_idx").on(table.subscriptionId),
  ],
);

export const signingKeys = sqliteTable(
  "signing_keys",
  {
    kid: text("kid").primaryKey(),
    alg: text("alg").notNull(),
    publicJwk: text("public_jwk").notNull(),
    status: text("status", { enum: ["active", "retired"] })
      .notNull()
      .default("active"),
    createdAt: createdAt(),
  },
  (table) => [check("signing_keys_status_check", sql`${table.status} IN ('active', 'retired')`)],
);

// ─── License keys (migration 0010, WT-14) ────────────────────────────────────────────────────

export const LICENSE_KEY_STATUSES = ["unredeemed", "redeemed", "revoked"] as const;

export const licenseKeys = sqliteTable(
  "license_keys",
  {
    id: text("id").primaryKey(),
    /** Groups the keys of one generation call (a label may be reused across batches). */
    batchId: text("batch_id").notNull(),
    /** SHA-256 (hex) of the plaintext key. The plaintext exists only in the generation response. */
    codeHash: text("code_hash").notNull(),
    /** Last four symbols of the key, for support lookups. */
    codeLast4: text("code_last4").notNull(),
    planCode: text("plan_code").notNull(),
    batchLabel: text("batch_label").notNull(),
    status: text("status", { enum: LICENSE_KEY_STATUSES }).notNull().default("unredeemed"),
    /** Staff user id. */
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(isoNow),
    expiresAt: text("expires_at"),
    redeemedAt: text("redeemed_at"),
    redeemedTenantId: text("redeemed_tenant_id"),
    redeemedByEmail: text("redeemed_by_email"),
    revokedAt: text("revoked_at"),
    revokeReason: text("revoke_reason"),
  },
  (table) => [
    uniqueIndex("license_keys_code_hash_unique").on(table.codeHash),
    index("license_keys_batch_idx").on(table.batchId, table.createdAt),
    index("license_keys_status_idx").on(table.status, table.createdAt),
    index("license_keys_last4_idx").on(table.codeLast4),
    check(
      "license_keys_status_check",
      sql`${table.status} IN ('unredeemed', 'redeemed', 'revoked')`,
    ),
  ],
);

// ─── Network peers (migration 0014, WT-9) ────────────────────────────────────────────────────
// One row per NetBird-mesh entity CloudBox has provisioned: a server (device_id set), a Connect
// client (user_id set, one per tenant membership), or the per-tenant "support access wired"
// marker (kind 'support', neither set — the single `cbx-support` gateway peer itself is not
// tenant-scoped and lives outside this table; a marker row records that a tenant's server group
// has been added to the standing support policy). D1 is authoritative for desired membership
// (master spec §4.8 "Network control ownership"); `netbird_peer_id` is filled once the real peer
// is observed joined (a future reconciliation job — out of scope while the server is mocked) and
// is null until then. `group_ids_json` records which NetBird group ids this row's setup key or
// policy contribution touched, for audit/debugging without calling back to NetBird.
export const NETWORK_PEER_KINDS = ["server", "client", "support"] as const;
export const NETWORK_PEER_STATUSES = ["not_configured", "pending", "active", "revoked"] as const;

export const networkPeers = sqliteTable(
  "network_peers",
  {
    id: text("id").primaryKey(),
    kind: text("kind", { enum: NETWORK_PEER_KINDS }).notNull(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    deviceId: text("device_id").references(() => devices.id),
    userId: text("user_id").references(() => customerUsers.id),
    netbirdPeerId: text("netbird_peer_id"),
    netbirdSetupKeyId: text("netbird_setup_key_id"),
    /** JSON array of NetBird group ids this row's setup key/policy contribution touched. */
    groupIdsJson: text("group_ids_json").notNull().default("[]"),
    status: text("status", { enum: NETWORK_PEER_STATUSES }).notNull().default("not_configured"),
    createdAt: createdAt(),
    updatedAt: text("updated_at").notNull().default(isoNow),
  },
  (table) => [
    index("network_peers_tenant_kind_idx").on(table.tenantId, table.kind),
    // One server row per device.
    uniqueIndex("network_peers_device_uq")
      .on(table.deviceId)
      .where(sql`${table.deviceId} IS NOT NULL`),
    // One client row per (tenant, user) — a Connect member has one client identity per tenant.
    uniqueIndex("network_peers_client_uq")
      .on(table.tenantId, table.userId)
      .where(sql`${table.kind} = 'client'`),
    // One support marker row per tenant.
    uniqueIndex("network_peers_support_uq")
      .on(table.tenantId)
      .where(sql`${table.kind} = 'support'`),
    check("network_peers_kind_check", sql`${table.kind} IN ('server', 'client', 'support')`),
    check(
      "network_peers_status_check",
      sql`${table.status} IN ('not_configured', 'pending', 'active', 'revoked')`,
    ),
  ],
);

// ─── Email providers (migration 0008, WT-12) ─────────────────────────────────────────────────

export const EMAIL_PROVIDER_KINDS = ["cloudflare_binding", "smtp", "log"] as const;

export const emailProviders = sqliteTable(
  "email_providers",
  {
    id: text("id").primaryKey().notNull(),
    name: text("name").notNull(),
    kind: text("kind", { enum: EMAIL_PROVIDER_KINDS }).notNull(),
    priority: integer("priority").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    fromAddress: text("from_address").notNull(),
    /** Non-secret fields only: `{host, port, secure, username}` for `smtp`, `{}` otherwise. */
    configJson: text("config_json").notNull().default("{}"),
    /** AES-256-GCM ciphertext/IV pair, base64. Null when the provider has no secret. */
    secretCiphertext: text("secret_ciphertext"),
    secretIv: text("secret_iv"),
    updatedBy: text("updated_by"),
    createdAt: text("created_at").notNull().default(isoNow),
    updatedAt: text("updated_at").notNull().default(isoNow),
  },
  (table) => [
    index("email_providers_enabled_priority_idx").on(table.enabled, table.priority),
    check(
      "email_providers_kind_check",
      sql`${table.kind} IN ('cloudflare_binding', 'smtp', 'log')`,
    ),
  ],
);

// ─── Backups (migration 0017, WT-19) ─────────────────────────────────────────────────────────
// master spec §23 (all subsections), §46; Slices 9.3-9.5 cloud halves. `backup_jobs` is the local
// backup's own metadata (§23.8 "backup success is not upload success" — job state tracks local
// verification separately from cloud upload/verify); `backup_artifacts` is the R2 object's state,
// one row per job once an upload attempt begins. Never delete the newest `cloud_verified`
// artifact per device regardless of policy (retention.ts).

export const BACKUP_JOB_KINDS = ["frequent", "nightly", "manual", "pre_upgrade"] as const;
export const BACKUP_JOB_STATES = [
  "created",
  "verified_local",
  "upload_started",
  "upload_completed",
  "cloud_verified",
  "retention_applied",
  "failed",
] as const;
export const RETENTION_CLASSES = ["recent", "daily", "weekly", "monthly", "yearly"] as const;
export const RESTORE_OUTCOMES = ["success", "failure", "partial"] as const;

/** Per-tenant retention policy (§23.7). No row = the tenant follows the global default stored at
 * `settings['backups.default_policy']` (resolved server-side by `backups/policy.ts`, never by the
 * client guessing). */
export const backupPolicies = sqliteTable("backup_policies", {
  tenantId: text("tenant_id")
    .primaryKey()
    .references(() => tenants.id),
  frequentHours: integer("frequent_hours").notNull().default(4),
  dailyKeep: integer("daily_keep").notNull().default(30),
  weeklyKeep: integer("weekly_keep").notNull().default(12),
  monthlyKeep: integer("monthly_keep").notNull().default(12),
  yearlyKeep: integer("yearly_keep").notNull().default(0),
  offsiteEnabled: integer("offsite_enabled", { mode: "boolean" }).notNull().default(true),
  updatedBy: text("updated_by"),
  updatedAt: text("updated_at").notNull().default(isoNow),
});

export const backupJobs = sqliteTable(
  "backup_jobs",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    deviceId: text("device_id")
      .notNull()
      .references(() => devices.id),
    kind: text("kind", { enum: BACKUP_JOB_KINDS }).notNull(),
    state: text("state", { enum: BACKUP_JOB_STATES }).notNull().default("created"),
    startedAt: text("started_at").notNull().default(isoNow),
    finishedAt: text("finished_at"),
    sourceDataset: text("source_dataset").notNull(),
    appVersion: text("app_version"),
    sizeBytes: integer("size_bytes"),
    sha256: text("sha256"),
    localPathHint: text("local_path_hint"),
    errorJson: text("error_json"),
  },
  (table) => [
    index("backup_jobs_tenant_device_idx").on(table.tenantId, table.deviceId, table.startedAt),
    index("backup_jobs_device_state_idx").on(table.deviceId, table.state),
    check(
      "backup_jobs_kind_check",
      sql`${table.kind} IN ('frequent', 'nightly', 'manual', 'pre_upgrade')`,
    ),
    check(
      "backup_jobs_state_check",
      sql`${table.state} IN ('created', 'verified_local', 'upload_started', 'upload_completed', 'cloud_verified', 'retention_applied', 'failed')`,
    ),
  ],
);

export const backupArtifacts = sqliteTable(
  "backup_artifacts",
  {
    id: text("id").primaryKey(),
    jobId: text("job_id")
      .notNull()
      .unique()
      .references(() => backupJobs.id),
    r2Key: text("r2_key").notNull().unique(),
    sizeBytes: integer("size_bytes"),
    sha256: text("sha256"),
    encryptionJson: text("encryption_json"),
    uploadedAt: text("uploaded_at"),
    verifiedAt: text("verified_at"),
    retentionClass: text("retention_class", { enum: RETENTION_CLASSES }),
    expiresAt: text("expires_at"),
    deletedAt: text("deleted_at"),
    /** In-flight R2 multipart upload id (owner addition, not in the spec's column list — needed
     * to resume `PUT .../parts/:n` and `POST .../complete` against the same R2 upload). Cleared
     * (left as-is; harmless) once `complete` succeeds. */
    multipartUploadId: text("multipart_upload_id"),
  },
  (table) => [
    index("backup_artifacts_job_idx").on(table.jobId),
    check(
      "backup_artifacts_retention_class_check",
      sql`${table.retentionClass} IS NULL OR ${table.retentionClass} IN ('recent', 'daily', 'weekly', 'monthly', 'yearly')`,
    ),
  ],
);

export const restoreTests = sqliteTable(
  "restore_tests",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    deviceId: text("device_id")
      .notNull()
      .references(() => devices.id),
    artifactId: text("artifact_id")
      .notNull()
      .references(() => backupArtifacts.id),
    performedBy: text("performed_by").notNull(),
    performedAt: text("performed_at").notNull().default(isoNow),
    outcome: text("outcome", { enum: RESTORE_OUTCOMES }).notNull(),
    notes: text("notes"),
  },
  (table) => [
    index("restore_tests_device_idx").on(table.deviceId, table.performedAt),
    index("restore_tests_tenant_idx").on(table.tenantId, table.performedAt),
    check(
      "restore_tests_outcome_check",
      sql`${table.outcome} IN ('success', 'failure', 'partial')`,
    ),
  ],
);
