// Owner: WT-0. The single Drizzle schema for D1. Other worktrees request columns via their handoff.
// Better Auth tables are generated (`pnpm auth:generate`) from src/auth; do not hand-edit them.
// Our timestamps are ISO-8601 UTC text; Better Auth's are its generated integer millis.
import { relations, sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

const isoNow = sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`;
const createdAt = () => text("created_at").notNull().default(isoNow);

// ─── Phase 0 (migrations 0001/0002, extended by 0003) ─────────────────────────────────────────

export const settings = sqliteTable("settings", {
  key: text("key").primaryKey().notNull(),
  valueJson: text("value_json").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const auditLog = sqliteTable(
  "audit_log",
  {
    id: text("id").primaryKey().notNull(),
    eventType: text("event_type").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    actorType: text("actor_type").notNull(),
    actorId: text("actor_id").notNull(),
    action: text("action").notNull(),
    beforeJson: text("before_json"),
    afterJson: text("after_json"),
    createdAt: text("created_at").notNull(),
    actorTenantId: text("actor_tenant_id"),
    correlationId: text("correlation_id"),
    source: text("source"),
  },
  (table) => [
    index("audit_log_created_at_idx").on(table.createdAt),
    index("audit_log_entity_idx").on(table.entityType, table.entityId, table.createdAt),
    index("audit_log_actor_tenant_idx").on(table.actorTenantId, table.createdAt),
  ],
);

// ─── Identity: two separate systems, nothing shared (owner decision, ADR 0002) ─────────────────
// Generated by `auth@1.7.6 generate` from src/auth/cli.ts (staff: password + twoFactor) and
// src/auth/cli-customer.ts (customers: emailOTP). Regenerate both when either plugin list changes.

// Staff identity (/api/ops/auth): staff_users, staff_sessions, staff_accounts, staff_verifications,
// staff_two_factor, staff_rate_limit.
export const staffUsers = sqliteTable("staff_users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" }).default(false).notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  twoFactorEnabled: integer("two_factor_enabled", { mode: "boolean" }).default(false),
});

export const staffSessions = sqliteTable(
  "staff_sessions",
  {
    id: text("id").primaryKey(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => staffUsers.id, { onDelete: "cascade" }),
  },
  (table) => [index("staffSessions_userId_idx").on(table.userId)],
);

export const staffAccounts = sqliteTable(
  "staff_accounts",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => staffUsers.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("staffAccounts_userId_idx").on(table.userId)],
);

export const staffVerifications = sqliteTable(
  "staff_verifications",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("staffVerifications_identifier_idx").on(table.identifier)],
);

export const staffTwoFactor = sqliteTable(
  "staff_two_factor",
  {
    id: text("id").primaryKey(),
    secret: text("secret").notNull(),
    backupCodes: text("backup_codes").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => staffUsers.id, { onDelete: "cascade" }),
    verified: integer("verified", { mode: "boolean" }).default(true),
    failedVerificationCount: integer("failed_verification_count").default(0),
    lockedUntil: integer("locked_until", { mode: "timestamp_ms" }),
  },
  (table) => [
    index("staffTwoFactor_secret_idx").on(table.secret),
    index("staffTwoFactor_userId_idx").on(table.userId),
  ],
);

export const staffRateLimit = sqliteTable("staff_rate_limit", {
  id: text("id").primaryKey(),
  key: text("key").notNull().unique(),
  count: integer("count").notNull(),
  lastRequest: integer("last_request").notNull(),
});

export const staffUsersRelations = relations(staffUsers, ({ many }) => ({
  staffSessionss: many(staffSessions),
  staffAccountss: many(staffAccounts),
  staffTwoFactors: many(staffTwoFactor),
}));

export const staffSessionsRelations = relations(staffSessions, ({ one }) => ({
  staffUsers: one(staffUsers, {
    fields: [staffSessions.userId],
    references: [staffUsers.id],
  }),
}));

export const staffAccountsRelations = relations(staffAccounts, ({ one }) => ({
  staffUsers: one(staffUsers, {
    fields: [staffAccounts.userId],
    references: [staffUsers.id],
  }),
}));

export const staffTwoFactorRelations = relations(staffTwoFactor, ({ one }) => ({
  staffUsers: one(staffUsers, {
    fields: [staffTwoFactor.userId],
    references: [staffUsers.id],
  }),
}));

// Customer identity (/api/auth): customer_users, customer_sessions, customer_accounts,
// customer_verifications, customer_rate_limit.
export const customerUsers = sqliteTable("customer_users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" }).default(false).notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const customerSessions = sqliteTable(
  "customer_sessions",
  {
    id: text("id").primaryKey(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => customerUsers.id, { onDelete: "cascade" }),
  },
  (table) => [index("customerSessions_userId_idx").on(table.userId)],
);

export const customerAccounts = sqliteTable(
  "customer_accounts",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => customerUsers.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("customerAccounts_userId_idx").on(table.userId)],
);

export const customerVerifications = sqliteTable(
  "customer_verifications",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("customerVerifications_identifier_idx").on(table.identifier)],
);

export const customerRateLimit = sqliteTable("customer_rate_limit", {
  id: text("id").primaryKey(),
  key: text("key").notNull().unique(),
  count: integer("count").notNull(),
  lastRequest: integer("last_request").notNull(),
});

export const customerUsersRelations = relations(customerUsers, ({ many }) => ({
  customerSessionss: many(customerSessions),
  customerAccountss: many(customerAccounts),
}));

export const customerSessionsRelations = relations(customerSessions, ({ one }) => ({
  customerUsers: one(customerUsers, {
    fields: [customerSessions.userId],
    references: [customerUsers.id],
  }),
}));

export const customerAccountsRelations = relations(customerAccounts, ({ one }) => ({
  customerUsers: one(customerUsers, {
    fields: [customerAccounts.userId],
    references: [customerUsers.id],
  }),
}));

// ─── Staff and permissions ────────────────────────────────────────────────────────────────────

export const STAFF_ROLES = ["super_admin", "admin", "support", "read_only"] as const;
const staffRoleCheck = sql`('super_admin', 'admin', 'support', 'read_only')`;

export const staffMembers = sqliteTable(
  "staff_members",
  {
    userId: text("user_id")
      .primaryKey()
      .references(() => staffUsers.id),
    role: text("role", { enum: STAFF_ROLES }).notNull(),
    createdBy: text("created_by"),
    createdAt: createdAt(),
    /** 1 until the staff member replaces the initial password an admin set (ADR 0009, WT-1). */
    mustChangePassword: integer("must_change_password", { mode: "boolean" })
      .notNull()
      .default(true),
  },
  (table) => [check("staff_members_role_check", sql`${table.role} IN ${staffRoleCheck}`)],
);

export const permissions = sqliteTable("permissions", {
  key: text("key").primaryKey(),
  description: text("description").notNull(),
});

export const rolePermissions = sqliteTable(
  "role_permissions",
  {
    role: text("role", { enum: STAFF_ROLES }).notNull(),
    permissionKey: text("permission_key")
      .notNull()
      .references(() => permissions.key),
  },
  (table) => [
    primaryKey({ columns: [table.role, table.permissionKey] }),
    check("role_permissions_role_check", sql`${table.role} IN ${staffRoleCheck}`),
  ],
);

// ─── Plans ────────────────────────────────────────────────────────────────────────────────────

export const PLAN_STATUSES = ["active", "retired"] as const;
export const PLAN_CURRENCIES = ["INR", "USD", "EUR", "GBP", "AED"] as const;

// `status`/`term_days` were added to an existing table by migration 0009 via `ALTER TABLE ADD
// COLUMN`, which D1/SQLite cannot pair with an inline CHECK constraint (that requires a full
// table rebuild). Migration 0009 enforces both instead with BEFORE INSERT/UPDATE triggers
// (`plans_status_check_insert/_update`, `plans_term_days_check_insert/_update`) — there is no
// declarative CHECK on this table in D1, so none is declared here either. Migration 0011's
// `currency` column follows the same pattern (`plans_currency_check_insert/_update`); the price
// amounts and `max_addon_users` are plain non-negative integers, bounds enforced by Zod only
// (same as `offline_grace_days`/`renewal_warning_days` above — no DB trigger for those either).
export const plans = sqliteTable("plans", {
  code: text("code").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  maxDevices: integer("max_devices").notNull(),
  maxManagedUsers: integer("max_managed_users").notNull(),
  featuresJson: text("features_json").notNull(),
  offlineGraceDays: integer("offline_grace_days").notNull(),
  renewalWarningDays: integer("renewal_warning_days").notNull(),
  status: text("status").notNull().default("active"),
  /** Days a redeemed subscription runs (owner addition; redemption semantics are WT-14's). */
  termDays: integer("term_days").notNull().default(365),
  /** Minor units (e.g. paise/cents) for `currency`. */
  priceAmount: integer("price_amount").notNull().default(0),
  /** ISO 4217. */
  currency: text("currency").notNull().default("INR"),
  /** Minor units, per additional managed user per term. */
  addonUserPriceAmount: integer("addon_user_price_amount").notNull().default(0),
  /** 0 = no add-on users allowed on this plan. */
  maxAddonUsers: integer("max_addon_users").notNull().default(0),
  createdAt: createdAt(),
  updatedAt: text("updated_at").notNull().default(isoNow),
});

// ─── Tenancy ──────────────────────────────────────────────────────────────────────────────────

export const TENANT_STATUSES = [
  "trial",
  "provisioning",
  "active",
  "past_due",
  "suspended",
  "cancelled",
  "archived",
] as const;

export const tenants = sqliteTable(
  "tenants",
  {
    id: text("id").primaryKey(),
    publicCode: text("public_code").notNull().unique(),
    displayName: text("display_name").notNull(),
    legalName: text("legal_name"),
    status: text("status", { enum: TENANT_STATUSES }).notNull().default("provisioning"),
    primaryContactEmail: text("primary_contact_email"),
    supportContactEmail: text("support_contact_email"),
    billingContactEmail: text("billing_contact_email"),
    timezone: text("timezone").notNull().default("UTC"),
    maintenanceWindowJson: text("maintenance_window_json"),
    renewalWarningDays: integer("renewal_warning_days").notNull().default(30),
    backupPolicyJson: text("backup_policy_json"),
    planCode: text("plan_code").references(() => plans.code),
    notes: text("notes"),
    createdAt: createdAt(),
    updatedAt: text("updated_at").notNull().default(isoNow),
    archivedAt: text("archived_at"),
  },
  (table) => [
    index("tenants_status_idx").on(table.status, table.createdAt),
    check(
      "tenants_status_check",
      sql`${table.status} IN ('trial', 'provisioning', 'active', 'past_due', 'suspended', 'cancelled', 'archived')`,
    ),
  ],
);

export const MEMBERSHIP_STANDINGS = ["owner", "admin", "user"] as const;

export const tenantMemberships = sqliteTable(
  "tenant_memberships",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    userId: text("user_id")
      .notNull()
      .references(() => customerUsers.id),
    standing: text("standing", { enum: MEMBERSHIP_STANDINGS }).notNull(),
    status: text("status", { enum: ["active", "revoked"] })
      .notNull()
      .default("active"),
    invitedBy: text("invited_by"),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex("tenant_memberships_tenant_user_uq").on(table.tenantId, table.userId),
    index("tenant_memberships_user_idx").on(table.userId, table.status),
    check(
      "tenant_memberships_standing_check",
      sql`${table.standing} IN ('owner', 'admin', 'user')`,
    ),
    check("tenant_memberships_status_check", sql`${table.status} IN ('active', 'revoked')`),
  ],
);

// ─── Devices and enrollment ───────────────────────────────────────────────────────────────────

export const devices = sqliteTable(
  "devices",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    name: text("name").notNull(),
    status: text("status", { enum: ["enrolled", "revoked", "transferred"] })
      .notNull()
      .default("enrolled"),
    devicePublicKeyJwk: text("device_public_key_jwk").notNull(),
    deviceKeyThumbprint: text("device_key_thumbprint").notNull().unique(),
    keyProtection: text("key_protection", { enum: ["tpm", "software"] }).notNull(),
    hostname: text("hostname").notNull(),
    windowsBuild: text("windows_build"),
    agentVersion: text("agent_version"),
    lastSeenAt: text("last_seen_at"),
    lastHealthJson: text("last_health_json"),
    enrolledAt: text("enrolled_at").notNull().default(isoNow),
    revokedAt: text("revoked_at"),
  },
  (table) => [
    index("devices_tenant_status_idx").on(table.tenantId, table.status),
    check("devices_status_check", sql`${table.status} IN ('enrolled', 'revoked', 'transferred')`),
    check("devices_key_protection_check", sql`${table.keyProtection} IN ('tpm', 'software')`),
  ],
);

export const enrollmentTokens = sqliteTable(
  "enrollment_tokens",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    tokenHash: text("token_hash").notNull().unique(),
    label: text("label").notNull(),
    createdBy: text("created_by").notNull(),
    expiresAt: text("expires_at").notNull(),
    redeemedAt: text("redeemed_at"),
    redeemedDeviceId: text("redeemed_device_id").references(() => devices.id),
    revokedAt: text("revoked_at"),
    createdAt: createdAt(),
  },
  (table) => [index("enrollment_tokens_tenant_idx").on(table.tenantId, table.createdAt)],
);

export const deviceCredentials = sqliteTable(
  "device_credentials",
  {
    id: text("id").primaryKey(),
    deviceId: text("device_id")
      .notNull()
      .references(() => devices.id),
    tokenHash: text("token_hash").notNull().unique(),
    createdAt: createdAt(),
    revokedAt: text("revoked_at"),
  },
  (table) => [index("device_credentials_device_idx").on(table.deviceId)],
);

// ─── Subscriptions and entitlements ───────────────────────────────────────────────────────────

export const subscriptions = sqliteTable(
  "subscriptions",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    planCode: text("plan_code")
      .notNull()
      .references(() => plans.code),
    // `pending` (migration 0010, WT-14): plan assigned, no dates until the first server activates.
    status: text("status", {
      enum: ["pending", "trial", "active", "past_due", "suspended", "cancelled"],
    }).notNull(),
    validFrom: text("valid_from"),
    validUntil: text("valid_until"),
    maxManagedUsers: integer("max_managed_users").notNull(),
    /**
     * Add-on managed users beyond the plan's base `max_managed_users`, bought at
     * `plans.addon_user_price_amount` each per term (migration 0011). Capped at
     * `plans.max_addon_users`; effective limit = `max_managed_users + addon_users`. Added by
     * `ALTER TABLE ADD COLUMN`, so a constant default only — the `<= max_addon_users` bound is
     * data-dependent (another table) and is enforced by the API, not a DB CHECK.
     */
    addonUsers: integer("addon_users").notNull().default(0),
    featuresJson: text("features_json").notNull(),
    offlineGraceDays: integer("offline_grace_days").notNull(),
    renewalWarningDays: integer("renewal_warning_days").notNull(),
    createdAt: createdAt(),
    updatedAt: text("updated_at").notNull().default(isoNow),
  },
  (table) => [
    index("subscriptions_tenant_status_idx").on(table.tenantId, table.status),
    check(
      "subscriptions_status_check",
      sql`${table.status} IN ('pending', 'trial', 'active', 'past_due', 'suspended', 'cancelled')`,
    ),
    check(
      "subscriptions_dates_check",
      sql`${table.status} = 'pending' OR (${table.validFrom} IS NOT NULL AND ${table.validUntil} IS NOT NULL)`,
    ),
  ],
);

export const entitlements = sqliteTable(
  "entitlements",
  {
    id: text("id").primaryKey(),
    subscriptionId: text("subscription_id")
      .notNull()
      .references(() => subscriptions.id),
    deviceId: text("device_id")
      .notNull()
      .references(() => devices.id),
    generation: integer("generation").notNull(),
    claimsJson: text("claims_json").notNull(),
    /** Compact JWE. Never logged, never returned to the admin UI. */
    token: text("token").notNull(),
    issuedBy: text("issued_by").notNull(),
    issuedAt: text("issued_at").notNull().default(isoNow),
    validUntil: text("valid_until").notNull(),
    revokedAt: text("revoked_at"),
  },
  (table) => [
    uniqueIndex("entitlements_device_generation_uq").on(table.deviceId, table.generation),
    index("entitlements_subscription_idx").on(table.subscriptionId),
  ],
);

export const SIGNING_KEY_PURPOSES = ["entitlement", "release"] as const;

export const signingKeys = sqliteTable(
  "signing_keys",
  {
    kid: text("kid").primaryKey(),
    alg: text("alg").notNull(),
    publicJwk: text("public_jwk").notNull(),
    status: text("status", { enum: ["active", "retired"] })
      .notNull()
      .default("active"),
    /**
     * Migration 0016 (WT-18): which signer this key belongs to — `entitlement` (WT-5,
     * `ENTITLEMENT_SIGNING_JWK`) or `release` (WT-18, `RELEASE_SIGNING_JWK`). Added by `ALTER
     * TABLE ADD COLUMN`, which D1/SQLite cannot pair with an inline CHECK (that needs a full table
     * rebuild) — enforced by BEFORE INSERT/UPDATE triggers instead, the same pattern migration
     * 0009 uses for `plans.status`/`plans.currency`; no declarative CHECK is declared here either.
     */
    purpose: text("purpose").notNull().default("entitlement"),
    createdAt: createdAt(),
  },
  (table) => [check("signing_keys_status_check", sql`${table.status} IN ('active', 'retired')`)],
);

// ─── OTA releases (migration 0016, WT-18) ────────────────────────────────────────────────────
// Master spec §18, §45; Slices 10.1–10.4. `manifest_json` is the plain (never-secret) payload for
// server-side reads; `manifest_jws` is the signed envelope (`@cloudbox/update-contracts`) served to
// devices and verified by them. Neither is confidential, unlike `entitlements.token`.

export const RELEASE_COMPONENTS = ["agent", "status", "setup", "connect"] as const;
export const RELEASE_CHANNELS = ["development", "pilot", "stable", "pinned"] as const;
export const RELEASE_STATUSES = ["draft", "pilot", "stable", "withdrawn"] as const;

export const releases = sqliteTable(
  "releases",
  {
    id: text("id").primaryKey(),
    component: text("component", { enum: RELEASE_COMPONENTS }).notNull(),
    version: text("version").notNull(),
    channel: text("channel", { enum: RELEASE_CHANNELS }).notNull(),
    manifestJson: text("manifest_json").notNull(),
    manifestJws: text("manifest_jws").notNull(),
    packageR2Key: text("package_r2_key").notNull(),
    packageSha256: text("package_sha256").notNull(),
    packageSize: integer("package_size").notNull(),
    minAgentVersion: text("min_agent_version"),
    rollbackOf: text("rollback_of"),
    notes: text("notes"),
    status: text("status", { enum: RELEASE_STATUSES }).notNull().default("draft"),
    createdBy: text("created_by").notNull(),
    createdAt: createdAt(),
    promotedAt: text("promoted_at"),
    withdrawnAt: text("withdrawn_at"),
    withdrawReason: text("withdraw_reason"),
  },
  (table) => [
    index("releases_component_channel_idx").on(table.component, table.channel, table.status),
    index("releases_created_at_idx").on(table.createdAt),
    check(
      "releases_component_check",
      sql`${table.component} IN ('agent', 'status', 'setup', 'connect')`,
    ),
    check(
      "releases_channel_check",
      sql`${table.channel} IN ('development', 'pilot', 'stable', 'pinned')`,
    ),
    check(
      "releases_status_check",
      sql`${table.status} IN ('draft', 'pilot', 'stable', 'withdrawn')`,
    ),
  ],
);

export const RELEASE_ASSIGNMENT_SCOPES = ["device", "tenant", "fleet_percent"] as const;

export const releaseAssignments = sqliteTable(
  "release_assignments",
  {
    id: text("id").primaryKey(),
    releaseId: text("release_id")
      .notNull()
      .references(() => releases.id),
    scope: text("scope", { enum: RELEASE_ASSIGNMENT_SCOPES }).notNull(),
    deviceId: text("device_id").references(() => devices.id),
    tenantId: text("tenant_id").references(() => tenants.id),
    percent: integer("percent"),
    createdBy: text("created_by").notNull(),
    createdAt: createdAt(),
  },
  (table) => [
    index("release_assignments_release_idx").on(table.releaseId),
    index("release_assignments_device_idx").on(table.deviceId),
    index("release_assignments_tenant_idx").on(table.tenantId),
    check(
      "release_assignments_scope_check",
      sql`${table.scope} IN ('device', 'tenant', 'fleet_percent')`,
    ),
  ],
);

export const RELEASE_RESULT_STATES = [
  "assigned",
  "downloaded",
  "verified",
  "installed_healthy",
  "installed_unhealthy",
  "rolled_back",
  "failed_download",
  "failed_validation",
  "deferred_active_users",
  "deferred_maintenance",
] as const;

export const releaseResults = sqliteTable(
  "release_results",
  {
    id: text("id").primaryKey(),
    releaseId: text("release_id")
      .notNull()
      .references(() => releases.id),
    deviceId: text("device_id")
      .notNull()
      .references(() => devices.id),
    state: text("state", { enum: RELEASE_RESULT_STATES }).notNull(),
    detailJson: text("detail_json"),
    reportedAt: text("reported_at").notNull().default(isoNow),
  },
  (table) => [
    index("release_results_release_idx").on(table.releaseId, table.reportedAt),
    index("release_results_device_idx").on(table.deviceId, table.reportedAt),
    check(
      "release_results_state_check",
      sql`${table.state} IN ('assigned', 'downloaded', 'verified', 'installed_healthy', 'installed_unhealthy', 'rolled_back', 'failed_download', 'failed_validation', 'deferred_active_users', 'deferred_maintenance')`,
    ),
  ],
);

// ─── License keys (migration 0010, WT-14) ────────────────────────────────────────────────────

export const LICENSE_KEY_STATUSES = ["unredeemed", "redeemed", "revoked"] as const;

export const licenseKeys = sqliteTable(
  "license_keys",
  {
    id: text("id").primaryKey(),
    /** Groups the keys of one generation call (a label may be reused across batches). */
    batchId: text("batch_id").notNull(),
    /** SHA-256 (hex) of the plaintext key. The plaintext exists only in the generation response. */
    codeHash: text("code_hash").notNull(),
    /** Last four symbols of the key, for support lookups. */
    codeLast4: text("code_last4").notNull(),
    planCode: text("plan_code").notNull(),
    batchLabel: text("batch_label").notNull(),
    status: text("status", { enum: LICENSE_KEY_STATUSES }).notNull().default("unredeemed"),
    /** Staff user id. */
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(isoNow),
    expiresAt: text("expires_at"),
    redeemedAt: text("redeemed_at"),
    redeemedTenantId: text("redeemed_tenant_id"),
    redeemedByEmail: text("redeemed_by_email"),
    revokedAt: text("revoked_at"),
    revokeReason: text("revoke_reason"),
  },
  (table) => [
    uniqueIndex("license_keys_code_hash_unique").on(table.codeHash),
    index("license_keys_batch_idx").on(table.batchId, table.createdAt),
    index("license_keys_status_idx").on(table.status, table.createdAt),
    index("license_keys_last4_idx").on(table.codeLast4),
    check(
      "license_keys_status_check",
      sql`${table.status} IN ('unredeemed', 'redeemed', 'revoked')`,
    ),
  ],
);

// ─── Email providers (migration 0008, WT-12) ─────────────────────────────────────────────────

export const EMAIL_PROVIDER_KINDS = ["cloudflare_binding", "smtp", "log"] as const;

export const emailProviders = sqliteTable(
  "email_providers",
  {
    id: text("id").primaryKey().notNull(),
    name: text("name").notNull(),
    kind: text("kind", { enum: EMAIL_PROVIDER_KINDS }).notNull(),
    priority: integer("priority").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    fromAddress: text("from_address").notNull(),
    /** Non-secret fields only: `{host, port, secure, username}` for `smtp`, `{}` otherwise. */
    configJson: text("config_json").notNull().default("{}"),
    /** AES-256-GCM ciphertext/IV pair, base64. Null when the provider has no secret. */
    secretCiphertext: text("secret_ciphertext"),
    secretIv: text("secret_iv"),
    updatedBy: text("updated_by"),
    createdAt: text("created_at").notNull().default(isoNow),
    updatedAt: text("updated_at").notNull().default(isoNow),
  },
  (table) => [
    index("email_providers_enabled_priority_idx").on(table.enabled, table.priority),
    check(
      "email_providers_kind_check",
      sql`${table.kind} IN ('cloudflare_binding', 'smtp', 'log')`,
    ),
  ],
);
